# -*- coding: utf-8 -*-
"""Yolov2-custom

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yBcyjVP2yoSaYQT3r1K-IFldTUVLFgVW
"""

from google.colab import drive
drive.mount('/content/gdrive')

!/usr/local/cuda/bin/nvcc --version

!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
!sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
!sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
!sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
!apt-get update
!apt-get -y install cuda-10.2

!pip3 install torch
!pip3 install torchvision

!tar -xzvf /content/gdrive/MyDrive/darknet/cudnn/cudnn-10.2-linux-x64-v8.2.2.26.tgz -C /usr/local/

!git clone https://github.com/AlexeyAB/darknet.git

# Commented out IPython magic to ensure Python compatibility.
# %ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/darknet/
!sed -i 's/OPENCV=0/OPENCV=1' Makefile             #opencv=0 -> opencv=1 로 바꿔준다
!sed -i 's/GPU=0/GPU=1' Makefile                   #gpu=0 -> gpu=1 로 바꿔준다
!sed -i 's/CUDNN=0/CUDNN=1' Makefile               #cudnn=0 -> cudnn=1 로 바꿔준다
!sed -i 's/CUDNN_HALF=0/CUDNN_HALF=1' Makefile     #cudnn_half -> cudnn_half=1 로 바꾸준다

!make

!cp ./darknet /content/gdrive/MyDrive/darknet/bin/darknet
!chmod +x ./darknet

!chmod +x /content/gdrive/MyDrive/darknet/bin/darknet/darknet

cd /content/gdrive/MyDrive/darknet/bin/darknet

pwd

!wget https://pjreddie.com/media/files/darknet19_448.conv.23

!sudo apt install dos2unix

!find . -print | xargs dos2unix

cd /content/gdrive/MyDrive/darknet/bin/darknet

pwd

cd ..

!./darknet detector train /content/gdrive/MyDrive/darknet/bin/darknet/cfg/obj.data /content/gdrive/MyDrive/darknet/bin/darknet/cfg/yolov4-custom.cfg darknet19_448.conv.23 -dont_show

# Commented out IPython magic to ensure Python compatibility.
def imShow(path):
  import cv2
  import matplotlib.pyplot as plt
#   %matplotlib inline

  image = cv2.imread(path)
  height, width = image.shape[:2]
  resized_image = cv2.resize(image, (3*width, 3*height), interpolation = cv2.INTER_CUBIC)

  fig = plt.gcf()
  fig.set_size_inches(18, 10)
  plt.axis("off")
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()

def upload():
  from google.colab import files
  uploaded = files.upload()
  for name, data in uploaded.items():
    with open(name, 'wb') as f:
      f.write(data)
      print('saved file', name)
def download(path):
  from google.colab import files
  files.download(path)

!./darknet detect /content/gdrive/MyDrive/darknet/bin/darknet/backup/yolov2-tiny-voc_last.weights /content/gdrive/MyDrive/darknet/bin/darknet/data/obj/1.jpg
imShow('3.jpg')

!./darknet detector train /content/darknet/cfg/obj.data\
                          /content/darknet/cfg/yolov2-tiny-voc.cfg\